import type { LayoutConfig } from "../types";

/** Template 1 — বিজয় গৌরব (Victory Day) */
export const VICTORY_LAYOUT: LayoutConfig = {
  version: 1,
  themeId: "victory",
  tone: "triumphant",
  palette: {
    bgFrom: "#03362a",
    bgTo: "#0b6b4f",
    primary: "#0b6b4f",
    secondary: "#e63a2e",
    accent: "#f6c445",
    ink: "#10201a",
    paper: "#fff6de",
    headline: "#fff6de",
    headlineStroke: "#03261c",
    panel: "#04372a",
    panelText: "#fff6de",
    footer: "#03261c",
    footerText: "#fff6de",
  },
  motifs: ["sunburst", "sun", "flags", "paddy", "doves", "stars", "border", "grain"],
  frame: "arch",
  photoFilter: "none",
  photoLayouts: {
    "1": [{ x: 340, y: 176, w: 520, h: 566, z: 3 }],
    "2": [
      { x: 122, y: 214, w: 448, h: 510, z: 3, rotate: -2 },
      { x: 630, y: 214, w: 448, h: 510, z: 3, rotate: 2 },
    ],
    "3": [
      { x: 392, y: 172, w: 416, h: 552, z: 3 },
      { x: 58, y: 304, w: 292, h: 384, z: 2, rotate: -3 },
      { x: 850, y: 304, w: 292, h: 384, z: 2, rotate: 3 },
    ],
  },
  slots: {
    dateText: { x: 390, y: 40, w: 420, h: 68, size: 34, minSize: 20, weight: 700, nowrap: true },
    headline: { x: 60, y: 752, w: 1080, h: 326, size: 214, minSize: 64, lineHeight: 1.1, valign: "middle" },
    subheadline: { x: 134, y: 1090, w: 932, h: 62, size: 38, minSize: 18, weight: 600 },
    creditLabel: { x: 132, y: 1172, w: 168, h: 46, size: 30, minSize: 16, weight: 700, nowrap: true },
    plate: { x: 116, y: 1226, w: 968, h: 208, nameSize: 76, designationSize: 40, partySize: 34, gap: 0, align: "center" },
    location: { x: 60, y: 1516, w: 1080, h: 62, size: 34, minSize: 18, weight: 600, nowrap: true },
  },
  headline: { fontId: "anek", bodyFontId: "hind", style: "stroke" },
  defaults: {
    headline: "মহান বিজয় দিবস",
    subheadline: "১৬ ডিসেম্বর — লাল-সবুজের গৌরবের দিন",
    creditLabel: "প্রচারে",
  },
  colorways: [
    { id: "flag-green", name: "Flag Green", nameBn: "লাল-সবুজ", palette: {} },
    {
      id: "sunrise-red",
      name: "Sunrise Red",
      nameBn: "রক্তিম সূর্য",
      palette: {
        bgFrom: "#4a0d0a",
        bgTo: "#b8261c",
        primary: "#0b6b4f",
        secondary: "#f6c445",
        accent: "#ffe08a",
        headlineStroke: "#3a0806",
        panel: "#3a0a08",
        footer: "#2c0705",
      },
      motifs: ["sunburst", "sun", "flags", "paddy", "doves", "stars", "border", "grain"],
    },
    {
      id: "ivory-emerald",
      name: "Ivory Emerald",
      nameBn: "হাতির দাঁত ও পান্না",
      palette: {
        bgFrom: "#f9f3e2",
        bgTo: "#e2d6b4",
        primary: "#0b6b4f",
        secondary: "#d9342b",
        accent: "#c8961e",
        ink: "#10201a",
        paper: "#fff8e6",
        headline: "#0b6b4f",
        headlineStroke: "#fff8e6",
        panel: "#0a4d3a",
        panelText: "#fff6de",
        footer: "#073d2e",
      },
      motifs: ["sunburst", "sun", "flags", "paddy", "doves", "border", "grain"],
    },
    {
      id: "midnight-gold",
      name: "Midnight Gold",
      nameBn: "মধ্যরাত ও সোনালি",
      palette: {
        bgFrom: "#050b14",
        bgTo: "#0d2b3a",
        primary: "#0e5a4a",
        secondary: "#e63a2e",
        accent: "#f2c14e",
        headline: "#ffe9a8",
        headlineStroke: "#04070d",
        panel: "#07141f",
        footer: "#03070d",
      },
      motifs: ["sunburst", "sun", "flags", "paddy", "doves", "stars", "border", "grain"],
    },
  ],
};
