import { TEMPLATE_PRESETS, type OccasionId } from "@poster/shared";

/** Static marketing renders of each template (generated by `npm run samples -w @poster/api`). */
export interface Sample {
  slug: string;
  title: string;
  titleBn: string;
  occasion: OccasionId;
  src: string;
  alt: string[];
}

export const SAMPLES: Sample[] = TEMPLATE_PRESETS.map((p) => ({
  slug: p.slug,
  title: p.title,
  titleBn: p.titleBn,
  occasion: p.occasionType,
  src: `/samples/${p.slug}.jpg`,
  alt: [`/samples/${p.slug}-v1.jpg`, `/samples/${p.slug}-v2.jpg`],
}));

export const sampleFor = (slug: string): Sample | undefined => SAMPLES.find((s) => s.slug === slug);
